name: Build and Deploy

on:
  push:
    branches:
      - main # Или ваша ветка, например, master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Укажите нужную версию Node.js

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: npm run build # Замените на вашу команду сборки

    - name: Deploy to Hosting via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }} # Или используйте key: ${{ secrets.SSH_KEY }} для ключа SSH
        script: |
          cd /new.idel-almaty.kz
          # Здесь команды для удаления старых файлов, если это необходимо
          # Например, rm -rf * (осторожно с этой командой, убедитесь в корректности пути)
          # Используйте команды для загрузки новых файлов, например, через rsync или scp
